# Generated by Django 5.1.4 on 2025-06-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='left',
            field=models.ImageField(default='wefe', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='right',
            field=models.ImageField(default='wefew', upload_to=''),
            preserve_default=False,
        ),
    ]
