# Generated by Django 5.1.4 on 2025-06-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=9207773847, max_length=12),
            preserve_default=False,
        ),
    ]
