# Generated by Django 5.1.4 on 2025-06-25 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(upload_to='home_paage_images'),
        ),
        migrations.AlterField(
            model_name='home',
            name='left',
            field=models.ImageField(upload_to='home_paage_images'),
        ),
        migrations.AlterField(
            model_name='home',
            name='right',
            field=models.ImageField(upload_to='home_paage_images'),
        ),
    ]
